### ISSUE TITLE
Compatibility with powershell 6

### ISSUE THREAD

**Issue by DigitalCog** [jfriant/snipe-it-collector#1]
The powershell functions do not appear to work with powershell core (6.0) or later. According to the changes on powershell 6, they did not bring the Get-WmiObject functions over to the version according to [this docs page](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-7). However, swapping Get-WmiObject with Get-CimInstance will resolve the issue. Tested this fix and confirmed working with powershell 5 as well.

I can make a pull request if you would like

**Comment by jfriant** [comment]
Thank you for the suggestion.  It's an easy fix to make.  I'm not using Powershell 6 yet, but it's worked on all the instances of 5 that I tested.  I'll go ahead and commit a change.
